/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.codesoom.demo;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

// 스프링부트 애플리케이션이라는 것을 표시
@SpringBootApplication
public class App {
    public static void main(String[] args) {
        // 어떤 클래스를 실행할 것인지, 인자를 어떻게 넘겨줄 것인지
        SpringApplication.run(App.class, args);
    }
}
